Add director
Lady-Kapriz/java-filmorate pull request #8
Opened 2022-12-03 05:58 UTC by Malcevfs

Прошу провести ревью, коллеги :)

2022-12-03 06:58 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    @DeleteMapping("{id}")
возможно понадобится добавить "/"

2022-12-03 07:06 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    @DeleteMapping("{id}")
Исправлено :)

2022-12-03 07:13 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +        if (director.getName().isEmpty() || director.getName().equals(" ")) {
я думаю весь блок if можно заменить на isBlank

2022-12-03 07:14 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +    public Director updateDirector(Director director) {
можно добавить validate(director)

2022-12-03 07:14 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +
лишний пробел) ревьюеры бывают на этот счет дотошными

2022-12-03 07:15 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +
пробел

2022-12-03 07:21 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
пробел лишний

2022-12-03 07:39 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>          final String sqlQuery = "select * from films f " +
для единообразия можно переменную перенести в блок трай

2022-12-03 07:40 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>                  "left join mpa m on f.mpa_id = m.mpa_id";
надо разобраться фильмы и лайки доходят до фильма или нет...

2022-12-03 07:41 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +//                "left join film_director fd on fd.film_id = f.film_id " +
код в комментах лучше удалить

2022-12-03 07:46 UTC, BAnatoliy requested changes
все окей, мелочи можно подкорректировать

2022-12-03 19:37 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandler.java
> +    public ErrorResponse handleMpaNotFoundException(final DirectorNotFoundException e) {
Нужно переименовать. Скопировал блок Mpa и оставил handleMpa

2022-12-03 19:38 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +
enter не нужен

2022-12-03 19:43 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +    private final JdbcTemplate jdbcTemplate;
private static final переменные всегда идут самые первые. объявление JdbcTemplate нужно перенести вниз, после статичных переменные

2022-12-03 19:49 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +        }
смысл от этого блока try {} catch {} ? 
в методе getDirectorById уже есть валидация по id (<=0) и есть try catch на случай отсутствия такого id в БД

2022-12-03 20:29 UTC, Lady-Kapriz requested changes
Нужно исправить замечания

2022-12-03 20:29 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +
пустые строки между методами не нужны. Нужно поправить выравнивание.

2022-12-03 20:29 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private final FilmDirectorDbStorage filmDirectorDbStorage;
не нужно имплементацию, нужно интерфейс.

2022-12-03 20:29 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        log.debug("У фильма {} удалены жанры", film.getName());
нужно изменить текст сообщени в логе. удаляешь режиссеров, а удаляются жанры )

2022-12-03 20:29 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmDirector/FilmDirectorDbStorage.java
> +        final String sqlQuery = "insert into film_director (film_id, director_id) values(?, ?)";
стоит добавить валидацию и проверять, что существует фильм с filmId и режисер с directorId. Пример валидации можно посмотреть в LikeDbStorage

2022-12-03 20:29 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmDirector/FilmDirectorDbStorage.java
> +        final String sqlQuery = "delete from film_director where film_id = ?";
аналогично, валидация filmId

2022-12-03 20:29 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmDirector/FilmDirectorDbStorage.java
> +        final String sqlQuery = "select d.DIRECTOR_ID, d.DIRECTOR_NAME from FILM_DIRECTOR fd " +
и тут валидация filmId

2022-12-03 20:29 UTC, Lady-Kapriz commented on src/main/resources/data.sql
> +-- INSERT INTO FILM_DIRECTOR (FILM_ID, DIRECTOR_ID) VALUES ('1','1');
а это вот все зачем? есть где-то информация, что должны быит такие фильмы и такие режисеры?

жанры и mpa были добавлены сюда потому, что они прописаны по ТЗ. 
Добавлять в БД данные для тестов не нужно.

2022-12-04 03:32 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +        if (director.getName().isEmpty() || director.getName().equals(" ")) {
Не получится. В проверках Postman есть пользователь с именем "пробел". Он в тесте должен вернуться с ошибкой

2022-12-04 03:39 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +
Ни один ревьювер ни разу не сделал мне замечание на счет пробелов между методами :) К тому же, все классы я выравниваю и форматирую в идее при помощи ctrl + alt + L - пробелы идея ставит сама.
Исправил, если вы считаете, что это должно быть не так

2022-12-04 03:41 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Этот пробел ставит автоматически так же идея. Не думаю, что это ошибка

2022-12-04 03:42 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
>                  "left join mpa m on f.mpa_id = m.mpa_id";
До фильма доходят и лайки и режисеры и MPA :) Тут нет ошибки - тесты POSTMAN проходят корректно

2022-12-04 03:42 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandler.java
> +    public ErrorResponse handleMpaNotFoundException(final DirectorNotFoundException e) {
Каюсь :) Исправил

2022-12-04 03:43 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +
+

2022-12-04 03:44 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +        System.out.println(director);
Забытый артефакт :) Удалил

2022-12-04 03:47 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +
мне ревьюер указывал, что между методами ставим пробелы, после последнего до } пробел не нужен. Вообщем можно не исправлять, только потом придется Маше все к единому виду привести, когда будут проект в целом проверять

2022-12-04 03:48 UTC, BAnatoliy commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
согласен!

2022-12-04 03:48 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +
Пустые строки в интерфейсах делает автоматика код стайла в Idea при нажатии ctrl + alt + L . Если обратишь внимание, то и в методах классов так же есть отступы - уверена, что это ошибка?

2022-12-04 04:05 UTC, Malcevfs commented on src/main/resources/data.sql
> +-- INSERT INTO FILM_DIRECTOR (FILM_ID, DIRECTOR_ID) VALUES ('1','1');
Эти строки в data.sql записаны для локальных тестов. Сейчас они закомичены. Попрошу их не удалять пока что, так как еще не весь функционал дописан. На финальном этапе написания функционала удалю их

2022-12-04 06:48 UTC, Lady-Kapriz requested changes
Попробуй исправить аннотацию валидации. 
Проверь пустые строки и выравнивание. Ревьюеры к этому обычно капризны, это всегда бросается в глаза. 

И повторю комментарий с предыдущего ревью:
Также для красоты кода предлагаю (и всем предложу) перенести sql запросы в класс, выделить их в статичные переменные.
Например,
private static final String SQL_SELECT_GET_DIRECTOR_BY_ID = "select * from directors where director_id = ?";
У нас уже будут классы, в которых мы вносим запросы в статические переменные (они получаются слишком громоздкие), поэтому предлагаю привести проект к общему виду (рефакторинг остальных классов также будет, но позже)

2022-12-04 06:48 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +        if (director.getName().isEmpty() || director.getName().equals(" ")) {
Попробуй заменить аннотацию @NotEmpty на @NotBlank (или просто ее добавить) и проверить

2022-12-04 06:48 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorStorage.java
> +
Нужно поправить выравнивание. Лишний отступ. Можно применить к файлу Ctrl + Alt + L (в windows точно)

2022-12-04 06:48 UTC, Lady-Kapriz commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmDirector/FilmDirectorDbStorage.java
> +
пустая строка

2022-12-04 06:48 UTC, Lady-Kapriz commented on src/main/resources/data.sql
> +INSERT INTO FILM_DIRECTOR (FILM_ID, DIRECTOR_ID) VALUES ('1','2');
Для локальных тестов есть файл data.sql по пути src/test/resources. Тестирование также проще проводить через JUnit

2022-12-04 10:25 UTC, Malcevfs commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +        if (director.getName().isEmpty() || director.getName().equals(" ")) {
isBlank

2022-12-06 13:53 UTC, Lady-Kapriz approved these changes

2022-12-06 14:32 UTC, BAnatoliy approved these changes

2022-12-06 14:45 UTC, merged